const transform = {
	"Alkmaar(Youth)": "Jong AZ Alkmaar",
	"Bruk-Bet Termalica Nieciecza": "Nieciecza",
	"Manchester United FC": "Man Utd",
	Thespakusatsu: "Thespakusatsu Gunma",
	"V-Varen Nagasaki": "Nagasaki",
	"West Ham United Reserve": "West Ham U23",
	"Liverpool Res.": "Liverpool U23",
	"LDU Quito": "LDU",
	"Orense SC": "Orense Sporting Club",
	"KTP Kotka": "KTP",
	"Kowa Viedade": "Cova da Piedade",
	Linkopings: "Linkopings FC (W)",
	"IFK Goteborg": "Kopparbergs/Goteborg (W)",
	"Gornik Leczna": "Gornik Zabrze",
	"Leon De Huanuco": "Leon",
	"Podbeskidzie Bielsko-Biala": "Podbeskidzie B-B",
	"Sheffield United FC": "Sheff Utd",
	Shmona: "Hapoel Kiryat Shmona",
	"Dallas Mavericks": "FC Dallas",
	"Montreal Impact": "Montreal",
	Washington: "DC Utd",
	"Al-Birah Institution": "Al-Birah",
	"SK Bann": "Brann",
	"Ad Cali": "Deportivo Cali",
	"Trugkucu Munchen": "SV Turkgucu-Ataspor",
	"Torpedo BelAZ": "Zhodino",
	"Dun. Streda": "Dunajska Streda",
	"FK Pohronie Ziar Nad Hronom Dolna Zdana": "Pohronie",
	"Melilla Baloncesto": "Melilla UD",
	"H. Ironi Rishon": "Hapoel Rishon Lezion",
	"Etar Veliko Tarnovo": "Etar",
	"Radnik Bijeljina": "Radnik Surdulica",
	TNS: "The New Saints",
	"Blackburn Rovers": "Blackburn",
	"QPR Park Rangers": "QPR",
	"Atl. Paranaense": "Atletico PR",
	"Kometa Brno": "FC Zbrojovka Brno",
	"FC Bastia Borgo": "FC Bastia-Borgo",
	"Arago de Sete": "Sete",
	Honka: "FC Honka Espoo (W)",
	"Aland UTD.": "Aland United (W)",
	"Al-Qadisiya": "Al-Qadsia",
	Paide: "Paide Linnameeskond",
	"Wehen Wiesbaden": "Wehen",
	"Atletico San Luis": "San Luis",
	Spenimur: "Spennymoor Town",
	Gloucester: "Gloucester City",
	"AC Goianiense": "Atletico GO",
	"Zweigen Kanazava": "Kanazava",
	"Stargrad Szczecinski": "Blektini Stargard",
	"Politehnica Iasi": "Iasi",
	Wolverhampton: "Wolves",
	"Metalac GM": "Metalac Gornji Milanovac",
	"Lok. Zagreb": "Lokomotiva",
	"U.A.N.L.- Tigres": "Tigres",
	"Manchester United Reserve": "Man Utd U23",
	"Al-Arabi Doha": "Al Arabi Kuwait",
	"Olympique Nimes": "Nimes",
	Kalev: "Tallinna Kalev",
	Tulevik: "Tulevik Viljandi",
	"Sport Boys Association": "Sport Boys (Per)",
	"Hapoel Jerusalem FC": "Hapoel Katamon",
	"Alianca Huanuko": "Alianza Universidad",
	"Costa-Rica": "Cost Rica",
	"Ipswich Town Reserve": "Ipswich U23",
	"Coventry U23": "Coventry City U23",
	Alania: "Alania Vladikavkaz",
	"Podbeskidzie Bielsko-Biala": "Podbeskidzie B-B",
	Zaglebie: "Zaglebie Lubin",
	"Al-Khor": "Al Khor",
	"Al Duhail": "Al-Duhail SC",
	"FC Carlos Stein": "C Stein",
	"Al-Birah Institution  ": "Al Birah",
	"Shabab Al Amar": "Markaz Shabab Al-Am'ari",
	"Hull City reserve": "Hull U23",
	"SC Dinamo 1948 SA 2": "Dinamo Bucharest II",
	Ампаро: "Amparo SP",
	Guarulhos: "Guarulhos SP",
	"Slask 2": "Slask Wroclaw II",
	"Bourg Peronn": "Bourg-en-Bresse",
	"Atletico Junior": "Junior FC Barranquilla",
	Puszcza: "Puszcza Niepolomice",
	"Termalica Bruk-Bet Nieciecza": "Nieciecza",
	Omsk: "FK Irtysh Omsk",
	"AS Saint-Etienne": "St Etienne",
	"Bosnia & Herzegovina": "Bosnia",
	"Avaldnsnes IL": "Avaldsnes (W)",
	"Arna-Bjornar": "Arna-Bjornar (W)",
	Lungbiu: "Lyngby",
	"Unia Svejenzi": "Unia Swarzedz",
	"Pogon Szczecin II": "MKS Pogon Szczecin II",
	"Olimpia Cluj-Napoca": "Olimpia Cluj (W)",
	Bargaului: "ACS Heniu Prundu Bargaului (W)",
	"Anderson G.": "Gary Anderson",
	"Sirl R.": "Ryan Searle",
	"Wade J.": "James Wade",
	"Durrant G.": "Glen Durrant",
	"Heta D.": "Damon Heta",
	"Cross R.": "Rob Cross",
	"Hamfrisi L.": "Luke Humphries",
	"Pryse G.": "Gerwyn Price",
	"Joisi R.": "Ryan Joyce",
	"Smith M.": "Michael Smith",
	"Rataiski K.": "Krzysztof Ratajski",
};

let converter = (key) => {
	if (transform[key]) {
		return transform[key];
	} else {
		return key;
	}
};
module.exports = { converter };
